### ISSUE TITLE
User survey for IMLS outcome-based reporting

### ISSUE THREAD

**Issue by rnedge** [PresConsUIUC/PSAP#115]
This is a requirement that as IMLS grantees we should attempt to meet.  Basically, what has been discussed is that we include a few (2-4; TBD) questions to new registrants (a link to a simple CITES UIUC survey w/ the registration email) to determine their level of knowledge regarding preservation, etc.  

Then, some 3 months after the account has been set up, they receive a follow-up email that asks whether they believe they have improved, and to what extent the PSAP has enabled them, etc.

This is likely to be something that is addressed and finessed in the final few months, but I just wanted to add it to the hopper now.

**Comment by areisemann** [comment]
I have made an imbedded Survey Monkey version of the survey and have now also made a Qualtrics version with a PresCon address that everyone can access.

**Comment by adolski** [comment]
Okay, so, after the user has signed in for the first time, and closed the welcome panel, they will see this:

![survey](https://cloud.githubusercontent.com/assets/6854505/7541595/2baf9e60-f57c-11e4-8abe-97e5dd85a89b.png)

I need someone to finish that text for me, as I have no idea what to say.

(The green button opens the survey in a new window/tab. Qualtrics does have an option to "embed the survey in the page," but I tried it out and it's pretty lame. This way will definitely work better.)

**Comment by jhain** [comment]
Awesome!  How about:

Please take our pre-use survey.  There are only four, short questions and the data collected will help us understand our users better so that we can not only continue to develop better services for the PSAP, but also better argue for future grant funding to expand and improve this project.  Thanks!
