### ISSUE TITLE
Link resource assessment questions to advanced help

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#140]
The resource tabs of the G:\AcqCatPres\PSAP\Scores\questionDependencies.xlsx spreadsheet need two new columns: one containing the corresponding Advanced Help URL fragment (e.g. "av-film") and another containing the corresponding Advanced Help URL anchor (e.g. "uniquecontent"). See Location and Institution tabs for examples.

**Comment by adolski** [comment]
@jamieviva Feel free to reassign this -- just didn't want it to be overlooked.

**Comment by jamieviva** [comment]
@adolski I must be missing something, I don't see this spreadsheet- my view of that directory:
![capture](https://cloud.githubusercontent.com/assets/6641487/6043416/b504c088-ac51-11e4-9046-9d117038ffdd.PNG)

**Comment by adolski** [comment]
@jamieviva Sorry, it's questionDependencies.xlsx - I wrote what it's called in my head instead of what it really is.

**Comment by jamieviva** [comment]
Should be linked and working now, I'll add content for LaserDiscs to optical media as I edit advanced help and plug in anchors as I go.

**Comment by adolski** [comment]
@jamieviva I'm seeing gaps in the following cells:

Institution E12-13, F12-13, E15, F15
Resource-AV J176-187, K176-187
Resource-Paper-Unbound J123-142
Resource-Paper-Bound J2

**Comment by jamieviva** [comment]
Thanks Alex, I'll address those today.
