### ISSUE TITLE
Full borders around all tables

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#148]
across the application, in the Institution, Locations, and Resources view screens -- fully enclosed with bold borders, like the Format ID Guide tables look.

Examples:

Borders: http://localhost:3000/format-id-guide/film#film35mm
No borders: http://localhost:3000/locations/1

**Comment by adolski** [comment]
Sorry @rnedge, you got outvoted 3-1 with one abstainer. ;)

**Comment by rnedge** [comment]
I want you all to remember this day: the day I, Ryan Nicholas Edge, turned against the PSAP. Remember.

**Comment by adolski** [comment]
@rnedge That needs to be a separate issue. "Add 'Enemies' section to About page"

**Comment by rnedge** [comment]
@adolski my mind is running wild with the potential wireframe I could
submit, but I'm afraid Visio does not support the appropriate signifiers



On Wednesday, January 21, 2015, adolski <notifications@github.com> wrote:

> @rnedge <https://github.com/rnedge> That needs to be a separate issue.
> "Add 'Enemies' section to About page"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PresConsUIUC/PSAP/issues/148#issuecomment-70891180>.
>


-- 
*Ryan*

**Comment by adolski** [comment]
@rnedge Yet another argument for Gliffy.

**Comment by rnedge** [comment]
@adolski perfect landing

*Ryan*
