### ISSUE TITLE
Factor temperature & humidity range scores into overall scores

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#191]

**Comment by adolski** [comment]
@jhain https://github.com/PresConsUIUC/PSAP/wiki/Scoring as requested

**Comment by jhain** [comment]
@adolski @jamieviva  temp and RH should be factored into the "location" section of the score.  Forgive my excel formatting, but don't know how else to show the math.

Location score (LS) =  ((sum of QS / # of questions) * 0.7 +( 0.15 * Temperature) + (0.15 * RH)
HOWEVER, in the scoring dependencies spreadsheet G:\AcqCatPres\PSAP\Scores\questiondependencies, which i assume is the master for this, there is NO QUESTION asking for annual avg temp.  is there in the actual programmed questions?  the total scoring weight int he question dependencies appears to be .15 short of 1.0, so it clearly SHOULD have been there.

**Comment by adolski** [comment]
@jhain Thank you, that makes sense, and answers my question.

For design simplicity reasons, temp/RH is a property of a location, entered on the "new location" or "edit location" page, rather than an assessment question.

Good catch about the location question weights only adding up to 85. We will need to adjust them to make them add up to 100. I will create a separate issue for that and assign you, and you can either handle it yourself, or assign someone else.
