### ISSUE TITLE
Add Resources Section

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#202]
Insert linked 'further resources' section for  FIDG

**Comment by jamieviva** [comment]
@jhain @areisemann How granular should I be with click-throughs to further resources? Do we want links for each format, or in the format class summaries?

**Comment by jhain** [comment]
sorry, been focusing on other projects this week.  personally, i think the format class in most cases should be sufficient.

**Comment by jamieviva** [comment]
completed by @areisemann
