### ISSUE TITLE
Institution CSV export takes forever

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#205]

**Comment by adolski** [comment]
Feedback requested on this:

Currently, the multiple-resource CSV export contains hundreds of columns: 20 or so for each property of the resources, plus one for each assessment question in the system, of which there are several hundred. This is necessary because different resources will have responses to different questions.

For technical reasons, generating this file is super slow. I could potentially modify the code to display a set of only the questions available to any of the resources' formats, but (without explaining, in the interest of keeping this brief) that would be a poor solution.

Presumably the main advantage of CSV is the ability to open it in Excel, but this data doesn't really benefit from Excel's features -- it's not chartable, for example. If the intent is to make data available in a format that can be imported into other systems, any programmer would prefer JSON, which is so much richer.

So, I propose retaining CSV export **excluding** assessment questions, and adding a JSON export that includes assessment questions. Does this sound OK?

**Comment by adolski** [comment]
This is in place now; if it ends up being a problem, we can revisit it then.

**Comment by jhain** [comment]
That works for me.  we are also exporting in XML, or no longer?

J

**Comment by adolski** [comment]
@jhain There is an ability to export individual resources in EAD XML format, but not multiple resources, for whatever reason. I could easily add that, though. I can demo how all of this exporting works at the meeting tomorrow.

**Comment by jhain** [comment]
I think a demo would help me wrap my head around the differences, though I totally get the cumbersome excel export.
