### ISSUE TITLE
Add Location Temperature Range Error

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#214]
When adding new location to new repository in existing institution or in new institution, encountered the following error:

Couldn't find TemperatureRange with ID=310 for Location with ID=

Tested with default temperature range (0-100) and entered other ranges. No difference in error.

![screen shot 2015-01-14 at 1 15 45 pm](https://cloud.githubusercontent.com/assets/6641487/5745604/aabcf356-9bef-11e4-90fc-3f9e7394c0f0.png)

**Comment by adolski** [comment]
@jamieviva, I think this is an older version of the app. Incidentally I discovered a completely unrelated bug, but it should work properly now.

Also, thanks for including the screenshot. For errors like this, if it's any less effort, all I need is the URL and instructions on how to trigger the error.
