### ISSUE TITLE
Dashboard dropdown menus do not expand

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#215]
Dropdown menus for institution selection, administration, and admin are highlighted but do not expand when selected.

![screen shot 2015-01-14 at 1 23 36 pm](https://cloud.githubusercontent.com/assets/6641487/5745750/9cdc93f8-9bf0-11e4-938f-6a505c05835d.png)

![screen shot 2015-01-14 at 1 20 56 pm](https://cloud.githubusercontent.com/assets/6641487/5745711/5aab6d10-9bf0-11e4-903f-a41d179fabe2.png)

**Comment by adolski** [comment]
I noticed the text in the nav bar - it changed to all-uppercase some time ago. Have you run a 'git pull' recently?

**Comment by jamieviva** [comment]
That just occurred to me a few minutes ago, I'm updating now.

**Comment by jhain** [comment]
Not i

**Comment by adolski** [comment]
Pretty sure this is a transient bug from a few months ago. Definitely no longer happening
