### ISSUE TITLE
Do something with "acceptable" column in FIDG tables

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#218]
On the following page: http://psap.library.illinois.edu/format-id-guide/archdrawingrepro

Most of the "storage environment" tables are missing values for the "acceptable" column. We should either fill those in if we have them, or remove that column heading.

Could be an issue on other pages too -- haven't checked.

**Comment by jamieviva** [comment]
Issue for all Architectural Drawing Reproduction formats except Blueprint

**Comment by jamieviva** [comment]
Resolved, final acceptable ranges pending @jhain approval

**Comment by jhain** [comment]
the FIDG and the scores have been updated to agree and the “acceptable” columns in the FIDG have been removed.  changes will go into effect with new upload of FIDG and links to questions depenencies table.
