### ISSUE TITLE
Scores for location temperature ranges (QID 1022)

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#219]
G:\AcqCatPres\PSAP\Scores\questionDependencies.xlsx

(Mentioned in #191)

**Comment by jhain** [comment]
Jamie - since you were working on the temp/RH values, can you take a stab at this? if not, i can look at it, but i get things done SO SLOWWWLLLLY :)

**Comment by jamieviva** [comment]
@jhain @adolski I added the avg temperature line and the ranges, but was unsure about what values to give each radio button, so I left the values blank.

**Comment by adolski** [comment]
@jamieviva I don't see QID 1022 in the Location tab -- did you maybe save the spreadsheet somewhere else?

**Comment by jhain** [comment]
@adolski @jamieviva looks to me that the ranges are pretty consistent and the radio buttons should be as follows: 0-32; 33-54; 55-72; 73+ (all degrees F)

**Comment by jhain** [comment]
@adolski; @jamieviva  sorry, my part is closed, but i think Alex still has something to resolve with Jamie

**Comment by jamieviva** [comment]
@adolski I'm not sure what happened, it looks fine from my machine in preservation - I tried saving it again, let me know if that works.

**Comment by adolski** [comment]
@jamieviva I see it now, thanks. We just need to get the scores figured out and then we can close this.

**Comment by adolski** [comment]
Going to merge this into #191.
