### ISSUE TITLE
Content for help landing page

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#220]
Need content for the page that will appear at /help. (Feel free to reassign)

**Comment by jhain** [comment]
@adolski outline (let me know if you prefer it formatted differently) available at: G:\AcqCatPres\PSAP\Design\HTML\AdvHelp "Advanced Help Landing Page Content"  @jamieviva, please review and let me know if i missed anything!

**Comment by adolski** [comment]
@jhain Thanks, I will translate this into the application as-is and we can go from there.
@jamieviva, if you make any changes, please make them with "track changes" enabled in Word and let me know.
