### ISSUE TITLE
EAD-XML and DC exports don't contain full description

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#223]
i signed in as "normal" and then pulled up sample assessed original document.  then i chose to export it as EAD-XML, which i then opened up in dreamweaver.  both the document's code as well as what you see when you run the code to test what it'll look like do not include details that i see on psap itself about the document.

it appears that the record's information about ink/media type, support type, and significance is not being carried over.  i think for ead the corresponding element tag is <did> with a sub-element of <physdesc> [www.loc.gov/ead/tglib/elements/did.html].  Right now the code skips over the area for format description (that you see in the non-exported version of the record).  It also skips over the area for notes, the section for significance, the section on rights, and the sections listing the creation date of the record and when it was last updated.

**Comment by areisemann** [comment]
i have also now noticed this is true for sample assessed bound paper resource too.  this information is missing from both of the record's EAD and DC exports.

**Comment by adolski** [comment]
Here is a summary of what is appearing where. If this is wrong in any way, please reopen and let me know.

Ink/media type: does not appear in EAD; appears in dc:format in DC

Support type: does not appear in EAD; appears in dc:format in DC

Notes: added to archdesc/did/note in EAD; already appear in dc:description in DC

Significance: does not appear in EAD/DC

Rights: added to archdesc/userestrict in EAD

Creation date: appears in EAD (the sample resources don't have them, but if you edit them to add dates, they do appear); does not appear in DC

Last updated date: does not appear in EAD/DC
