### ISSUE TITLE
Improve resource DC XML "type" value

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#227]
Originally part of #225:

In the DC XML resource export, The value "item", which is given as the dc:type, is used incorrectly. The values for dc:type should be things like "physical object", "image", or "sound." In this record's case, it seems like "text" or "image" would be the most appropriate.

**Comment by adolski** [comment]
@areisemann Can we come up with a list of DC type values and associate them with formats? So, in the questionDependencies.xlsx spreadsheet, we would add another column to the "Format Scores" tab with the DC type of that format.

**Comment by areisemann** [comment]
You mean like set up a list of possible values (i.e. provide users with a controlled vocabulary) from which they could pick options, both for the general dc:format element and then for the more descriptive dc:type?  I really like this idea.

**Comment by adolski** [comment]
There would be no new UI for this -- you could use values from a controlled vocabulary, or whatever, but they will be permanently bound to their corresponding format. So when a user ascribes the "Inkjet Print" format to an item, the item's DC type value will appear as X (whatever you entered for into that column in the spreadsheet for inkjet print).

**Comment by areisemann** [comment]
Well, a user would need first to identify the dc:format as: text or image or sound or video.  Then the dc:type (which is the value that psap is looking for/referring to when it uses the term "format") would be "inkjet print".

**Comment by adolski** [comment]
OK I think I get it now. So the spreadsheet would need a DC Format column, containing text, image, sound, video, or whatever for each PSAP format (a.k.a. DC type).

Once the user has ascribed a PSAP-format to an item, the system should be smart enough to know what DC-format that PSAP-format is without the user having to enter it separately.

**Comment by adolski** [comment]
Shouldn't have split this off from #225. My bad.
