### ISSUE TITLE
Unitdate for sample assessed bound paper resource

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#228]
i'm not sure sure if this is a bug or if this is essentially a typo.  the date given for this item is "30/50".  when you look at the EAD record, this value is entered for the <unitdate> element.  that is wierd.  given that the unitdate type is "bulk", the values entered should be a clearly recognizable range of years.  
--http://www.loc.gov/ead/tglib/elements/unitdate.html

**Comment by areisemann** [comment]
yes, it is strange.  farther on in the record, there is another <unitdate> element, which is written correctly (i.e. inclusive date specified and a year given) and which provides the value in the proper way (i.e. as a 4 number year).

**Comment by adolski** [comment]
The date range of this item was actually 30-50 (as in almost 2000 years ago). I changed the sample data to use only 4-digit years and changed the unitdate to be formatted with two years separated with a dash instead of a slash when there is a begin year & end year.
