### ISSUE TITLE
Assessment deleted when resource is edited

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#233]
After a resource is created and assessment is completed, if the resource is edited in any way (for example, adding an identifier or changing the title), the assessment is deleted and you have to complete it again for that resource. @areisemann you might want to be careful of this when presenting the application.

**Comment by adolski** [comment]
Fixed on the development branch. @areisemann, your branch still has this bug -- let me know if you want to get set up with the fix (there are a couple of commands that need typing). Otherwise, like @jamieviva said, be careful.
