### ISSUE TITLE
Add titles to advanced help pages

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#239]
For example, in av-audiocassette.html, the page begins like:

body
h2 id="uniquecontent" Unique Content /h2

We need to add a page title in an h1 element, like this:

body
h1 Audiocassettes /h1
h2 id="uniquecontent" Unique Content /h2

This needs to be done for all pages. Let me know if you have any questions; please go ahead and close this issue when finished.

**Comment by areisemann** [comment]
should i be naming the pages according to the html or according to what we'd like the title to be?  in other words, in your example, i'd use "audiocassette" if i followed the html and i'd use "audiocassettes" (or another phrase) if i wasn't.

**Comment by adolski** [comment]
Use what you'd like the title to be.

**Comment by areisemann** [comment]
ok, thanks.  AV section now finished.  Am moving on to the rest.
