### ISSUE TITLE
Overhaul interface

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#244]
I think this is really the key to solving the navigation problem throughout the site. I am envisioning a ubiquitous left accordion menu containing:

Dashboard
Institution Name (click + to see repositories)
Repository 1 (click + to see locations)
Location 1 (click + to see resources [or if there are too many, then don't show the +])

This would replace the institution pop-up menu in the header, and it might even supersede the breadcrumb.

Secondly, the pull-down menu goes away.
Thirdly, shortcut buttons somewhere at the top that (from #296):

- link to add repository
- link to assess
- link to assessment reports

**Comment by areisemann** [comment]
that sounds reasonable to me.  the institution pop-up header menu was a place that both testers weren't sure what to do with/how it related to the rest of the application's functions.

**Comment by jhain** [comment]
Agreed
