### ISSUE TITLE
Add alert about testing on main page

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#250]
Comments welcome on a message that will appear at the top of the main page when the app goes live on psap.library.illinois.edu:

"This is a beta version of the application. All functionality is in place, but some things may change. Feedback is welcome, but all use is at your own risk."

**Comment by rnedge** [comment]
That looks good to me

**Comment by jhain** [comment]
Agreed.

Sent from an itty-bitty keyboard

On Mar 3, 2015, at 2:06 PM, rnedge <notifications@github.com<mailto:notifications@github.com>> wrote:


That looks good to me
