### ISSUE TITLE
Beta-Testing Documentation

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#251]
I've now got the second beta-testing video, summarized notes, and extended commentary up on the Google Drive.  For videos and notes,  https://drive.google.com/?tab=wo&authuser=0#folders/0B7W6mO6l5-PsQlBWQXRmMnUxRFU [User Testing folder; User Testing, Round One subfolder].  For commentary on issues/bugs that came up for beta-testers, https://docs.google.com/document/d/1lZ5OCws49_B_nhxxDblwoMRNG9Rmc8-_qhsRIyrjc94/edit [User Testing folder; PSAP User Testing doc].  If you keep scrolling down in this document, you will also see the questions that I asked beta-testers.  

Alex, do you think this is adequate feedback, or should I schedule the Spurlock or Urbana Archives as part of Round One testing?  

Alex and Jennifer, are there any areas that you want me to find out specific or more in-depth details about that are not currently addressed by these questions?

**Comment by adolski** [comment]
There is tons of good info here, which we are going to have to translate into to-do items. Can we do this at our next long meeting on the 18th?

My inclination would be to hold off on Spurlock/Urbana Archives for round 1 as their feedback will be more useful in round 2.

**Comment by areisemann** [comment]
Ok, I'll hold off on scheduling Spurlock.
