### ISSUE TITLE
General Advanced Help Second Pass Edits

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#252]

**Comment by rnedge** [comment]
Hi @jamieviva, I have a minor edit for the Betamax entry of the FIDG http://psap.library.illinois.edu/format-id-guide/videotape#betamax

It currently states that Betamax is exclusively a commercial release format. If you could change that to "was a capture format and a commercial release video format", or something similar.  This was entirely my fault. And sorry to push this into Advanced Help, but I figured it was too trivial to warrant a new issue.

**Comment by jamieviva** [comment]
Thanks @rnedge, updated for the next release!
