### ISSUE TITLE
Orientation video(s)

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#256]
Think about how these could look, but hold off for now on actually creating them. Will be incorporated into #255.

**Comment by jamieviva** [comment]
Incorporate
what is an institution?
what is a repository?
what is a resource?

**Comment by jamieviva** [comment]
Sample video created, submit to @jhain and @areisemann for feedback

**Comment by adolski** [comment]
Let me know when the final version is ready so I can copy it into the application. (I know this is waiting on #244 among many others)

**Comment by jamieviva** [comment]
Videos are up! PSAP/Design/HTML/Videos - @adolski how do you want them embedded in the html? Should I use <video>? Do most browsers support that? Should we do it another way? Let me know.

**Comment by jamieviva** [comment]
@adolski I embedded the youtube playlist for now on the help landing page. I'm assigning this issue to you in case you want to host the videos ourselves and embed them. If not, you can just close it.

**Comment by adolski** [comment]
@jamieviva I think YouTube is the way to go. Thanks.
