### ISSUE TITLE
Rename Edit/Assess/Delete buttons to Edit Entity/Assess Entity/Delete Entity

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#258]

**Comment by jhain** [comment]
just making sure that we are renaming to "resource" not "entity"

**Comment by adolski** [comment]
On the resource page, there are six buttons: Export, Edit, Assess, Move, Clone, Delete. This button cluster is already quite wide. If we add "Resource" to the end of all of these, it will get very wide, and leave little room for the title on the left.

I think part of the reason for this issue was to resolve the ambiguity between the "Assess" button and the "Assessment" tab, but now that that tab has been renamed to "Score Summary," perhaps this is not a big deal after all. I will hold off on this one and await further instructions.

**Comment by areisemann** [comment]
You're right, Alex, that I don't think there's room to add it to each button on the Resource page.  What I'd been thinking was the best strategy would be to modify the Location page. It only has three buttons--resources, assessment, activity.  Perhaps this "Assessment" button can be renamed "Location Assessment"?  

What might work really well in addition to renaming Location Assessment is renaming the "Add Resource" button on the Location page as "Add Resource to be Assessed" ("to be Assessed" would be on a second line under the "Add Resource"). This way users would immediately know that it was the assessment button they were looking for, and it would also hint that you can't assess the resource without adding it first (another area of confusion for testers).

**Comment by adolski** [comment]
Unfortunately we can't do multi-line buttons, so I shortened that slightly to "Add Resource To Assess".
