### ISSUE TITLE
Add help text to Create Location panel

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#261]
"Think about how granular you want your location to be, and think about how you want to name it relative to the other locations in this repository."

**Comment by jhain** [comment]
add text on help hover tip to read:
"In most cases, location will be determined by architectural divisions, such as buildings, floors, or rooms, or other areas with discrete environmental conditions or security parameters.  If further granularity in locations is desired, a consistent naming conventions from largest to smallest entity separated by semicolons is suggested. For instance: "First Floor; Room 223; West Wall, Shelving Unit 2".
