### ISSUE TITLE
add better label to "extent" field

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#264]
on basic question label, change "extent" to "extent (resource size or duration (if time based))

**Comment by adolski** [comment]
@jhain Now that #254 is fixed, take a look at the hovertip for this one and let me know if you change your mind on this issue. Otherwise, I'll go ahead with it.

**Comment by jhain** [comment]
change hovertip to read, more simply "Extent indicates the quantity and physical nature of a resource" and keep examples.
