### ISSUE TITLE
consider how we add dates

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#269]
discuss how to enter 'unknown" for date, as well as "ca." if possible.  In help, be sure that we cover how to enter a century, range, etc.  user was able add "ca." to a single year field - so field right now is text? not limited to YYYY format.

**Comment by adolski** [comment]
#264 is fixed (date help hovertip works).

**Comment by jhain** [comment]
change hovertip to start with "The date value follows...." part.  @jamieviva  will work on text for advanced help to give concrete examples to click through to.

**Comment by areisemann** [comment]
I've added new content to both the user manual and the metadata doc to reflect how we'd like dates entered.
