### ISSUE TITLE
Welcome Modal Panel

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#271]
Text for panel:

Welcome! Thank you for registering as a new PSAP user. We did our best to make this application as intuitive as possible, but sometimes things can get tricky. We encourage you to take a look at our short introductory video and explore the user manual. We know you’re excited to get started, so if you want to take a shot on your own, you can always get back to our help later.

One big favor before you begin: please help us continue to develop useful tools by giving us some information about your current preservation knowledge.

**Comment by jamieviva** [comment]
user testing panel created, located at PSAP/Design/HTML/WelcomePanel

**Comment by adolski** [comment]
Thanks, @jamieviva, the updated welcome panel is now in the application. I am referencing the .mp4 file at its original URL for now -- #256 will take it from here.
