### ISSUE TITLE
Wrong answers for optical media assessment question

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#272]
While attempting to assess a CD/DVD, the multiple choices provided for the question "have you performed any data checks/ checksums on the encoded data?" are: metal, cardboard, glass, and unsure.  I'm pretty sure that these are not the proper choices.  

If you're curious, I entered a value of "unsure".  The perfect answer was apparently metal.

**Comment by jhain** [comment]
Huh…. Yeah, there’s something very wrong there… I’ll look into it.

j

**Comment by areisemann** [comment]
i found that question/answer combo on each optical media assessment form so it seems to be format-wide and not just cd/dvd-specific.

**Comment by adolski** [comment]
It looks like these options are supposed to be associated with QID 424, but 472 and 484 also have them.

**Comment by adolski** [comment]
This is a questionDependencies.xlsx issue, not an app issue. Changing assignment to @jhain -- feel free to reassign.

**Comment by jhain** [comment]
OK. will fix next wek

**Comment by jhain** [comment]
OK, QID 424 is correct.  Q 472 and 484 should be "Yes	1	No	0.25	Unsure	0.4" but i cannot edit the file from here easily.  can somebody replace these with the appropriate answer?

**Comment by adolski** [comment]
Thanks @jhain, this is now fixed.
