### ISSUE TITLE
change where link for help in upper right of application links to

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#275]
@jamieviva @adolski we need to change the landing page for the help button - currently goes to digested advanced help (for lack of a better term).  change to HTML landing page for all things help - with intro text providing context for each mode of help - ie. user manual, basic help, advanced help, camtasia videos, and format ID guide.  Jamie will draft content and get ready for alex to implement for next milestone.

**Comment by jamieviva** [comment]
Was waiting on absolute links - @adolski should I just insert relative links? Will that throw things off?

**Comment by adolski** [comment]
@jamieviva I will need to adjust the links when I import this page into the application, so as long as I can tell where a link is supposed to point -- like, <a href="/help/whatever">.

**Comment by jamieviva** [comment]
needs videos embedded, links updated, then will be ready to go live
