### ISSUE TITLE
Add lang attribute to <html> element

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#277]
In most/all cases, the language is not specified [<html lang="en">/< lang="en-US">] vs. [<html>] in the code (e.g. https://psap.library.illinois.edu/format-id-guide/officeprintcopy).  To make sure that website is accessible as possible, the language needs to be added to each html file.

**Comment by adolski** [comment]
No need to do this -- I just need to add it in one place and it will appear in every page throughout the site, thanks to the magic of Ruby on Rails.

**Comment by areisemann** [comment]
ok.  well, it's now been added individually to everything in the FIDG.  i'll let your code take care of the AdvHelp/etc then.
