### ISSUE TITLE
add additional text to "additional information" label 

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#284]
to better describe value of metadata and link to advanced help topic

**Comment by jamieviva** [comment]
How about: Click through for more information on the context of this question

**Comment by jamieviva** [comment]
@adolski please change advanced help links that currently say 'additional information' to "Click through for more information on the context of this question."

**Comment by adolski** [comment]
@jamieviva Are these the links in the assessment question hovertips that say "more information"?
