### ISSUE TITLE
Make changes to help splash page

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#286]
Modify to reorder the help per suggestions
Add 'get started' resource, add to list
Add framework for videos
Have it ready to go in HTML

**Comment by jamieviva** [comment]
Ready to go except for embedded videos

**Comment by jamieviva** [comment]
Available here: /AcqCatPres/PSAP/Design/HTML/help-landing-page.html

**Comment by adolski** [comment]
@jamieviva Should this be reopened and assigned to me?

**Comment by jamieviva** [comment]
@adolski I was going to wait until I had a couple of videos and content for Getting Started, then create an issue for you to publish it, if thats cool?

**Comment by adolski** [comment]
@jamieviva Cool.
