### ISSUE TITLE
Integrate Getting Started content

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#292]
To help users make decisions -- decision tree style?

Link to from help

**Comment by rnedge** [comment]
Hi @jamieviva, I was just using BitCurator's quickstart guide yesterday and really appreciated its economy and simplicity. It's just an in-browser PDF, with links. http://wiki.bitcurator.net/downloads/BitCurator-Quickstart.pdf 


Just thoughts.

**Comment by areisemann** [comment]
hmm, that looks like basically they've strung together a number of slides into a single pdf.  the explanatory text makes the whole document look a bit cluttered to me--maybe this type of presentation would work better with parts of the user manual instead.

**Comment by jamieviva** [comment]
thanks for the tip @rnedge - I like their concise "what you'll need" list, think we're going to go with something a little more ikea-instructions graphic, but I agree with @areisemann that there might be room for something like this in the user manual

**Comment by jamieviva** [comment]
Preliminary design created, pending review
PSAP/Design/HTML/Getting Started/getting-started.html

**Comment by jamieviva** [comment]
approved. needs updated links

**Comment by jamieviva** [comment]
Links updated.

**Comment by adolski** [comment]
@jamieviva, this is great. What software did you use to create the GIFs? Camtasia?

(I ask because I might have to re-do them now that the new left menu is in place...)

**Comment by jamieviva** [comment]
@adolski - thanks!! I actually used photoshop to make them -- don't worry about re-doing them, I think the gist of it is conveyed in the existing gifs (also, it takes forever - I removed as many frames as possible so there wouldn't be lag when the page loaded).

**Comment by adolski** [comment]
Just noticed that step 1 is missing a clip.

**Comment by jamieviva** [comment]
@adolski okay, I'm on it.

**Comment by jamieviva** [comment]
@adolski the clip has been added to the html file, though it needs a size adjustment to match the other ones.
