### ISSUE TITLE
Add page on vendors and where to buy stuff

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#295]
add to supplementary section

**Comment by areisemann** [comment]
Is this going to be structured based on my spreadsheet of recommended materials?

**Comment by jhain** [comment]
I will use that as a resource, but I also have content that I have alrady developed for other purposes that i can pull from.

**Comment by areisemann** [comment]
Excellent.  I'm glad we're going back to my original suggestion about having a vendor/where to get materials page.

**Comment by areisemann** [comment]
Jennifer's 3 short pieces = 3 docs of content now written/done.  all it needs is to be put into html, etc.

**Comment by jhain** [comment]
done except to be converted to HTML. located at: G:\AcqCatPres\PSAP\Design\HTML\add to FIDG from word

**Comment by jamieviva** [comment]
New html pages available in /PSAP/Design/HTML/FormatIDGuide-HTML/supplementary/

bring-professional.html
role-of-artifact.html
supplies.html
