### ISSUE TITLE
Change Dashboard

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#296]
Add:
-action links to facilitate navigation (we want the dashboard to be a navigation tool)
-link to add repository
-link to assess
-link to reports

**Comment by areisemann** [comment]
If you're changing the dashboard...perhaps just get rid of drop-down bar.  No one really uses it, and almost everyone overlooks it.  My tester today pointed out that it's easier to click on the tabs that you see--plus going to a drop-down bar means doing a whole extra step or two.

**Comment by adolski** [comment]
I'm going to fold this into #244, which is my big "interface overhaul" issue.

@areisemann, I agree -- the drop-down is going away.
