### ISSUE TITLE
Help text for assess quality of wind question (AV/videotape)

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#298]
My tester today could not read all of the content in the bubble.  It was clearly there, but she was not able to scroll down (within the pop-up bubble) to finish it.  This is the last question on the Assess Item form for this format.

**Comment by adolski** [comment]
Tested this with a format of Betamax in Chrome, Safari, and Firefox, and it works in each. @areisemann Is there anything unusual that you can think of about the browser you were using that causes this to happen? If not, could you show this to me next time we meet?

**Comment by jamieviva** [comment]
It could be that she needed to scroll down in the browser rather than in the help panel, this has happened to me before with some of the longer help content

**Comment by areisemann** [comment]
Jamie, you're right in that it can happen, but this time both the tester and I tried to scroll down at that point (with the mouse) without luck.  I haven't really seen it come up before (or at least not since the fall and one of the fixes made back then) so perhaps it was a temporary glitch.

**Comment by adolski** [comment]
I was using a trackpad, so I'll try a mouse.

**Comment by areisemann** [comment]
I can't replicate it again.  I think it must have been a momentary glitch.
