### ISSUE TITLE
Link to "significance" advanced help is broken

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#299]
The link from the "significance" hovertip in the resource edit from to the advanced help is broken. It's linking to /help/significance. For this to work, there must be a corresponding HTML file in the AdvHelp folder called significance.html, but it's missing. However, I noticed that it is present in the AdvHelp-2014-11-19 backup. At some point, it disappeared. So, we need to either add it back, or fix that link.

Possibly related background in #135.

@areisemann, feel free to reassign.

**Comment by areisemann** [comment]
i've put it back in the most recent advhelp folder and am about done with editing it.
