### ISSUE TITLE
Storyboard Central

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#301]
This issue is where I'm going to post storyboards for team approval.

Pending Storyboards:

General PSAP Overview
Login → Add Item 
Login → Add Collection
Understanding Reports
Interpreting Scores
Mobile Devices
PSAP for bibliographic control

**Comment by jamieviva** [comment]
General PSAP Overview [APPROVED]
![screen shot 2015-05-20 at 3 39 15 pm](https://cloud.githubusercontent.com/assets/6641487/7736201/c6fcdd94-ff07-11e4-9284-c0c0cee91310.png)

**Comment by jamieviva** [comment]
Understanding Reports

![screen shot 2015-05-20 at 4 29 11 pm](https://cloud.githubusercontent.com/assets/6641487/7736985/7569bae6-ff0d-11e4-9333-0e67ae0e7f67.png)
![screen shot 2015-05-20 at 4 29 22 pm](https://cloud.githubusercontent.com/assets/6641487/7736988/7a961f28-ff0d-11e4-8e50-db2867d00a8c.png)

**Comment by jamieviva** [comment]
Login to resource

I've found that storyboard doesnt really translate as well to actual video, so im doing quick & dirty prototypes instead - here's the login to resource version, apologies for jerkiness, choppy audio, and a training session in the background but i don't want to invest a lot of time since they're drafts.

http://people.lis.illinois.edu/~wttnbrg2/PSAP_login_to_resource_proto.mp4

**Comment by jamieviva** [comment]
Understanding scores

http://people.lis.illinois.edu/~wttnbrg2/scores_prototype.mp4

**Comment by adolski** [comment]
@jamieviva just a correction -- in scores_prototype.mp4, when you are showing the location score summary at 2:25, the score there is actually not dependent on any of the resources in the location -- it's the location score alone.

**Comment by jamieviva** [comment]
Thanks @adolski !! Really appreciate getting your feedback

**Comment by adolski** [comment]
@jamieviva I have some on PSAP_login_to_resource_proto.mp4 as well:

1) At 00:25, the sign-up process is a little more complicated than filling out the form and then signing in -- I know I described it somewhere, maybe an old github issue, but it's something like this:

1) User fills out form
2) User gets an email asking for confirmation
3) User confirms
4) psap@library.illinois.edu gets an email
5) Somebody on our side checks out user's data to see whether it looks legit, and decides to approve or not
6) Once approved, user gets an email containing a link to sign in
7) User creates their institution or selects an existing one
8) psap@library gets an email asking if this institution is legit and somebody decides to approve or not
9) Once approved, user is placed in this institution and the process is complete

2) At 00:35, I'd sign in as normal and not mention that dashboards look different (all non-admins will see the same dashboard)

3) At 1:08, users actually can't get to the show-all-institutions page at all -- only admins. They will either add or join an institution near the end of the sign-up process, and they can change it later by going to their user settings.

Everything after this point looks good. Thanks for doing these videos. I think they will be very helpful.

**Comment by jamieviva** [comment]
Awesome, thanks for the clarification @adolski !

**Comment by jhain** [comment]
Looks good to me!

**Comment by jhain** [comment]
Also good and I will add content to the user manual…

J
