### ISSUE TITLE
Option to clone resources with or without assessment data intact

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#302]
@jhain @areisemann @adolski -- When cloning an assessed resource, all of the metadata and assessment data is duplicated. If I remember correctly, @jhain was quite firm on only wanting resource metadata to be cloned, not assessment data. Please correct me & close this issue if I'm wrong!

**Comment by adolski** [comment]
@jhain will have to verify that, but I will add that if desired, it would be pretty simple to make the clone button into a pull-down menu with options of "Including Assessment" and "Without Assessment."

**Comment by jhain** [comment]
This works for me, if it's not too much trouble,.

Sent from an itty-bitty keyboard

On May 22, 2015, at 1:31 PM, adolski <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhain<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jhain&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=VmdTHodLILmRa-mKuNJG6pXvAPSt1Xuzf4ocbYKHlTE&m=qBL0jjftE0jxFD1wv75Mmxx3Y3vvF0ERKJC5OIRMnUw&s=L2KaKTo43k-H1M5BgHuH1pLvYwOA0sGyLxd_dFlKhk0&e=> will have to verify that, but I will add that if desired, it would be pretty simple to make the clone button into a pull-down menu with options of "Including Assessment" and "Without Assessment."
