### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#304]
Tried to create a new account, this happened
![screen shot 2015-06-03 at 1 43 57 pm](https://cloud.githubusercontent.com/assets/6641487/7968517/fa565694-09f6-11e5-8d5d-5ac7937f139d.png)

**Comment by adolski** [comment]
Please see the "Getting mail to work" section at https://github.com/PresConsUIUC/PSAP/wiki/PreparingADevelopmentEnvironment

Once that is done, you'll need to add a password to the mail.yml file. I can send that to you over Lync, Also, I can email some info about what is going on with regard to mail.

**Comment by adolski** [comment]
@jamieviva I didn't notice that you had just set up a gmail account for PSAP. There is already a Yahoo account, but use whichever you prefer. If you would rather use Yahoo, mail.yml is pre-filled with the Yahoo SMTP settings, so you need only fill in the password.

**Comment by jamieviva** [comment]
Thanks @adolski -- I actually just set it up in order to create a Youtube account for PSAP, but I'll accept a yahoo password, too :-)

**Comment by adolski** [comment]
@jamieviva That's cool. Can you make sure to store the username & password for that Google account somewhere? I don't know where -- I've been storing the yahoo mail account password on my own computer, encrypted, assuming that the G: drive might not be private enough, but that's not a good idea. Any ideas? (@jhain or @areisemann too)

**Comment by jamieviva** [comment]
@adolski @jhain @areisemann I was just thinking about this - I know that Ryan had a password document somewhere - maybe I'm naive, but I feel like we can just use the G: drive? I mean, who is going to mess with a freely available, open-source project with no sensitive information?

**Comment by jhain** [comment]
Aren’t there password management services we could put all this in?
