### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#305]
@jhain @areisemann are we keeping the user manual walkthroughs? I am pointing to different user manual features in the videos, and want to know if I can direct users to these. Additionally, I am using the anchors in /PSAP/Design/HTML/UserManual/usermanual.html to provide anchored links-- so please don't change those!

**Comment by jhain** [comment]
Amanda and I had talked about replacing MOST of the walkthrough with the “quick guide”, but that some screen shots/walk through would still be relevant…. Are there particular parts you want to retain? I hadn’t gotten to that yet, still changing temp/rh in the FIDG….

**Comment by jamieviva** [comment]
I was thinking that retaining a section on why institution and location and resources need to be assessed would be useful, I don't ever really go into context for that in the videos, I just emphasize that it has to be done, and I think it would be helpful to point users to the manual if they're confused about that.

**Comment by areisemann** [comment]
in terms of accessibility, it would be better to have information in
several places (one of which being written) instead of contained only in a
video.  those sections in the user manual wouldn't have to be long, but i
think it does makes sense to keep a description/explanation of them in it.

--AE

**Comment by jhain** [comment]
merging with previous user manual issue
