### ISSUE TITLE
reformat assessment report screen

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#306]
since the left hand navigation has overwritten the previous effort to transpose the "sub tabs" on the Assessment Report view and made them horizontal again, could we make the top line bold to further differentiate between the two hierarchies?

**Comment by adolski** [comment]
I have a change in progress that is going to move the assessment report screen to its own top-level page with an entry in the new left menu. (Resource search as well.) In its new place, the assessment report will have only one row of tabs. I know we didn't talk about this, but I think it's a logical next step that solves some usability issues that were still outstanding. More to come.

**Comment by jhain** [comment]
k

**Comment by adolski** [comment]
Change now in place.
