### ISSUE TITLE
User manual and advanced help buttons on non-logged-in screen

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#309]
After updating with the newest ruby/etc, I don't see either button on the top right-hand corner of the screen when I first get there.  (I _do_ see it once I've logged in, but before I do that, I don't.)

**Comment by adolski** [comment]
This was intentional, but I don't remember if it was my intent, or someone else's -- just want to confirm with @jhain that the help and user manual buttons in the top nav bar are supposed to be accessible even to logged-out users?

**Comment by jhain** [comment]
I don’t’ remember making a conscious decision either way, but it would be prefereable to ALWAYS have it display, whether logged in or not.

J
