### ISSUE TITLE
assess institution

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#312]
"assess institution" button goes nowhere.  
![screenshot assess institution](https://cloud.githubusercontent.com/assets/9726693/8415920/b79c3370-1e67-11e5-900e-e3372bdc37ec.jpg)

**Comment by jhain** [comment]
same happens with assess location....

**Comment by adolski** [comment]
For some reason, the location & institution assessment questions didn't get seeded into the database. I have no idea why not, or why there were no errors when I seeded it. In any case, they are in there now, and I just assessed an institution and location successfully.

**Comment by jhain** [comment]
Thx!
