### ISSUE TITLE
format type not saving?

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#313]
what fun it is to have this on a PC, but what problems i seem to be having :(

i enter a format for an item and save it, but then go to asses it and it tells me i haven't assigned  format type. Tried three times and it won't save. (FWIW, tried different formats and none seem to stick).

**Comment by rnedge** [comment]
Same for Edit Resource in Firefox on OSX

**Comment by jhain** [comment]
poo

**Comment by rnedge** [comment]
@adolski Here's what I can see in the activity log: 
Failed to update resource "Session 24C ; Disc 18," but failed:: undefined method `id' for nil:NilClass

**Comment by adolski** [comment]
Same issue as #312. My fault: duhhh, the database only gets seeded the **first** time the app is deployed... which happens to have been several months ago during a FIDG update. Updating all the fixture data seems to have fixed it, but I still need to go through and make sure that all the data is as it should be.
