### ISSUE TITLE
Irrelevant question display in Score Summary

### ISSUE THREAD

**Issue by rnedge** [PresConsUIUC/PSAP#316]
Re follow-up assessment questions not posed to the user (due to how they answered the primary question): could we gray these out or remove these from the Score Summary screen? 

![screen shot 2015-07-02 at 3 24 40 pm](https://cloud.githubusercontent.com/assets/6729329/8485908/0e0bf268-20cf-11e5-8933-a143b025a905.png)

**Comment by jamieviva** [comment]
@rnedge @adolski I also noticed that the bound book assessment had a question with wording that referred to "image"

**Comment by jhain** [comment]
That would be

“Are there additional copies, facsimiles, and/or access copies of this image?” (question 2 in the assessment)

I also wonder if we should add a response in that same section of “no container needed” for “Does this item have an appropriate enclosure in good condition?” that would score the same as “yes”.  Many books don’t NEED containers.  Thoughts?

**Comment by jamieviva** [comment]
I had the same thought when I was testing out a bound book collection -- but would all our users necessarily be able to evaluate whether a book needs a container or not?

**Comment by jhain** [comment]
I think that’s at least better than forcing them to say “no” when it doesn’t need one and docking them points when the lack of container is irrelevant.

j

**Comment by adolski** [comment]
Original issue fixed by hiding questions with no responses. The bound book thing continues in #329.
