### ISSUE TITLE
Remove logo images (UIUC, IMLS) from About page

### ISSUE THREAD

**Issue by rnedge** [PresConsUIUC/PSAP#317]
At the bottom of https://psap.library.illinois.edu/about 

These images don't actually display in Firefox, just the alt tags but they are unnecessary anyway due to the footer

![screen shot 2015-06-29 at 9 12 25 am](https://cloud.githubusercontent.com/assets/6729329/8487586/040fbc70-20db-11e5-8347-a615690ae134.png)

**Comment by jhain** [comment]
Oooh, that’s classy.

**Comment by adolski** [comment]
Just FYI, this is an issue with the retina versions of the images. Those of us stuck in 2012 can still see them. Still a bug, obviously
