### ISSUE TITLE
Links broken in User Manual "mapping to past perfect" 

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#318]
@jhain @adolski - were external resources moved into the user manual folder when this content was integrated? I get 404 errors for all links in the section.

**Comment by jhain** [comment]
Possibly not…. give me an example and I’ll work to fix that.

j

**Comment by adolski** [comment]
The broken links are to PDFs in a subfolder -- I will need to fix that.

**Comment by jhain** [comment]
k
