### ISSUE TITLE
FIDG HTML bundle is missing many sections

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#319]
The source files for the following sections are missing from FormatIDGuide-HTML\supplementary folder:

exhibitguide.html
collectiondev.html
disasterprepare.html
disasterresources.html
environmentalguide.html
exhibitguide.html
metadata.html
assessmentssurveys.html
presplanning.html
useaccess.html
inkothermedia.html
summary-avmedia.html
summary-archdrawrepro.html
summary-officeprintcopy.html
summary-photo.html

If these are supposed to be missing, then the links to them need to be removed from the FIDG TOC, which is something I have to do -- let me know.

**Comment by jhain** [comment]
I’ll look into this – some of these got moved into the user manual and I need to delete links in FIDG

**Comment by adolski** [comment]
Did we ever get this sorted out?

**Comment by jhain** [comment]
Yikes.  Dropped the ball on html.  Will make this a priority, but schedule's very full til w/o 9/7.

Sent from an itty-bitty keyboard

On Aug 25, 2015, at 5:31 PM, adolski <notifications@github.com<mailto:notifications@github.com>> wrote:


Did we ever get this sorted out?

**Comment by jhain** [comment]
OK, here's the skinny:

exhibitguide.html - moved to User Manual.  Delete from FIDG

collectiondev.html - moved to User Manual.  Delete from FIDG

disasterprepare.html - moved to User Manual.  Delete from FIDG

disasterresources.html - moved to User Manual.  Delete from FIDG

environmentalguide.html - moved to User Manual.  Delete from FIDG

exhibitguide.html - moved to User Manual.  Delete from FIDG

metadata.html - moved to User Manual.  Delete from FIDG

assessmentssurveys.html - moved to User Manual.  Delete from FIDG

presplanning.html - should have been moved over to User Manual, but looks like a goofed on this one. Will correct and let you know when i'm done.

useaccess.html - moved to User Manual.  Delete from FIDG

inkothermedia.html - i see this source file at: G:\AcqCatPres\PSAP\Design\HTML\FormatIDGuide-HTML\profiles\papersbooks\inkothermedia is this NOT what you're asking about?  if so, others will be wrong too....

summary-avmedia.html at G:\AcqCatPres\PSAP\Design\HTML\FormatIDGuide-HTML\profiles\avmedia\summary-avmedia

summary-archdrawrepro.html at G:\AcqCatPres\PSAP\Design\HTML\FormatIDGuide-HTML\profiles\papersbooks\archdrawingrepro

summary-officeprintcopy.html at G:\AcqCatPres\PSAP\Design\HTML\FormatIDGuide-HTML\profiles\papersbooks\officeprintcopy

summary-photo.html at G:\AcqCatPres\PSAP\Design\HTML\FormatIDGuide-HTML\profiles\photosimages\summary-photo

**Comment by jhain** [comment]
just added the lost "preservation planning" section to the user manual HTML file.  so unless i'm misunderstanding the above, i think we're good to go and you just need to delete the old reference to those sections in the FIDG?
