### ISSUE TITLE
Display of the top-most hover-tip text obscured (within modal)

### ISSUE THREAD

**Issue by rnedge** [PresConsUIUC/PSAP#325]
Place more padding at the top?
<img width="736" alt="screen shot 2015-08-20 at 10 05 05 am" src="https://cloud.githubusercontent.com/assets/6729329/9385251/5b03f302-4723-11e5-81fa-e34cad743fea.png">

**Comment by adolski** [comment]
Overriding the placement of these Bootstrap popovers is fairly arduous. I just removed the help text (since it is pretty redundant) leaving the "more information" link.
