### ISSUE TITLE
Assessment Report PDF opens, routes out

### ISSUE THREAD

**Issue by rnedge** [PresConsUIUC/PSAP#326]
Would we prefer this open in a new tab _blank? Not sure if this is the case for all PDFs...

**Comment by adolski** [comment]
There is a lot of discussion about target=_blank and different opinions about how/whether it should be used. I'm going by the [W3C Mobile Web Best Practices](http://www.w3.org/TR/mobile-bp/#d0e959), which says, "Do not cause pop-ups or other windows to appear and do not change the current window without informing the user."

I'm fine with violating that, though.

**Comment by rnedge** [comment]
You are a principled man, Alex. +1 for violating W3C in this particular
case. But may be best to defer to JHT...



On Thursday, August 20, 2015, adolski <notifications@github.com> wrote:

> There is a lot of discussion about target=_blank and different opinions
> about how/whether it should be used. I'm going by the W3C Mobile Web Best
> Practices <http://www.w3.org/TR/mobile-bp/#d0e959>, which says, "Do not
> cause pop-ups or other windows to appear and do not change the current
> window without informing the user."
>
> I'm fine with violating that, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PresConsUIUC/PSAP/issues/326#issuecomment-133039740>.
>


-- 
*Ryan*

**Comment by jhain** [comment]
Just tried to logon to see what it currently looks like so as to respond and cannot get into the tool – ryan, can you logon?  I think there may be a server issue?

**Comment by rnedge** [comment]
Same here:

"

Gateway Timeout: can't connect to remote host

"


*Ryan*

**Comment by jhain** [comment]
Yep.  Alex, I know you’re away from your desk right now (tried IM), but when you get back, can you trouble shoot and see what’s up? I know easy-search was down earlier, not sure if this is somehow related?

J

**Comment by adolski** [comment]
I'm not sure if this is the case, because I didn't receive any notifications about it, but it looks like Apache (the front-end web server) was upgraded to a version that didn't like the current PSAP configuration. We are back online now.

**Comment by jhain** [comment]
forgive Luddite me, but i'm not sure what the question really is.  is it that it opens as a PDF view and not a new tab?

**Comment by adolski** [comment]
@jhain The question is whether the PDF assessment report should open in the same tab, or a new tab. (Or new window if the browser doesn't support tabs.)

**Comment by jhain** [comment]
I am fine with new tab.  Sorry to hold this up.

Sent from an itty-bitty keyboard

On Aug 25, 2015, at 5:31 PM, adolski <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhain<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jhain&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=VmdTHodLILmRa-mKuNJG6pXvAPSt1Xuzf4ocbYKHlTE&m=wEWHSqmUa7c0yyGrVCDt1Fs6msxy7Jt1Fsl1L5Q8Ig4&s=pp4BG3MC-opZGAtEYHtndYh-w1-8hx6xgVPVV3w4Wrw&e=> The question is whether the PDF assessment report should open in the same tab, or a new tab. (Or new window if the browser doesn't support tabs.)
