### ISSUE TITLE
Contact-all-users feature

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#327]

**Comment by adolski** [comment]
@jhain, could you take a look here and let me know if this "Email Confirmed Users" button will work for you: https://psap-stage.library.illinois.edu/users

The button will simply open a new email (using a mailto: link) with all confirmed users' email addresses in the bcc field.

**Comment by jhain** [comment]
Cannot access https://psap-stage.library.illinois.edu/users - forbidden domain :(

**Comment by adolski** [comment]
Yeah, psap-stage is restricted to campus IPs. Can you check from on campus?

(No rush, but, sometime before the launch)

**Comment by jhain** [comment]
Arg.  Is this the version that I can only access on a mac, or should I be able to get to this from my PC?

J

**Comment by adolski** [comment]
You can use anything, but only from on campus.

**Comment by adolski** [comment]
You can use anything, but only from on campus.

Scratch that, only from library PCs at Main & Oak St. and IllinoisNet wireless

**Comment by jhain** [comment]
My logon, or “norm” or “admin”?

j

**Comment by jhain** [comment]
email all users button works, assuming it's right now only BCCing an example email to "admin@example.org".
