### ISSUE TITLE
Add "about me" text to institution approval email

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#331]
Is there any (easy) way for me to tell if i am approving soembody who has just CREATED an institution vs. somebody is asking to join an existing institution?  from the automated approval workflow that's set up, i cannot tell. Seems to me i need to look more carefully and am more inclined to email somebody as opposed to just approve them if they are joining versus creating.

**Comment by adolski** [comment]
You are approving new users, and then approving their requests to join an institution. The new-user approval only happens once per user. The institution approval happens whenever they join or change their institution.

**Comment by jhain** [comment]
OK, per our chat:  The "about me" section on the login request page currently reads: "About You and Your Interest in the PSAP".  Change to "Tell us about your position, institution, and interest in the PSAP (this will help us to better approve your institutional affiliations later on)" or some such. am open to better wording.

**Comment by adolski** [comment]
Will do

**Comment by adolski** [comment]
Changes now live.

**Comment by jhain** [comment]
Cool, thx!
