### ISSUE TITLE
new user report

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#332]
i will need to be able to report to the IMLS about the users we have - do we save their submitted "about me" text when they request a logon? also, in the "users" view (https://psap.library.illinois.edu/users) can we also list the country that the institution is working from? i don't believe we ask this regional bit until they request an institution, correct?

**Comment by adolski** [comment]
Yes, we save the "about me" text. It's not displayed anywhere, though.

All the location information we have is contained in the institution's address. I don't recall whether we make the country mandatory, but we could probably look it up if it's missing anywhere.

I could compile this info pretty easily by running a database query -- just let me know.
