### ISSUE TITLE
Links to many FIDG Supplementary pages missing from index

### ISSUE THREAD

**Issue by rnedge** [PresConsUIUC/PSAP#334]
This might have been a conscious edit to the Format ID Guide index https://psap.library.illinois.edu/format-id-guide that I missed, but it appears that many of the Policies and Procedures pages' links (e.g. Exhibition, Environmental Guidelines, etc.) are missing. The pages themselves are still live.

**Comment by adolski** [comment]
Thanks for reporting, @rnedge. I believe these pages were supposed to have been removed as part of #319, as the content has been migrated to the User Manual. I removed them from the TOC, but I didn't delete them from the database, so it looks like I need to do that.
