### ISSUE TITLE
When a user joins an institution, email every other user in the institution to inform them

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#338]
(Waiting on @jhain for text for this)

**Comment by jhain** [comment]
actually, _I_ will manually email them, i believe - you will add the emails to the authorization request and then the PSAP manager will email the others to ask if ti's OK to add them.  

The canned text we talked about was the auto-generated email approving a person joining or creating an institution to add some text that would read something like:

You have successfully been added to "x" institution in the PSAP application.  Please remember that other people are open to join this institution. While we at PSAP try our best to make sure that members are only authorized if they actually belong to an institution, for your part please monitor users in your institution to ensure that membership is current and accurate.  If you question any PSAP user's right to be in your institution, do not hesitate to contact us at psap@library.illinois.edu.
