### ISSUE TITLE
Allow editing of "About" field for user under "Basic Information"

### ISSUE THREAD

**Issue by miriamcenteno** [PresConsUIUC/PSAP#339]
I need to be able to see the "About" field under the user's "Basic Information" screen and edit/add information that people have sent me via email.

**Comment by adolski** [comment]
@miriamcenteno Can you explain the second part of this, about editing/adding information?

**Comment by miriamcenteno** [comment]
I still have some users who created new accounts before the "About" field was made a required field. I am supposed to send them an email asking them for that information. I just got a reply email with more user information that I need to add to the "About" field.

**Comment by adolski** [comment]
Ah, I get it now, thanks.

**Comment by miriamcenteno** [comment]
Hi Alex,

Below is a screengrab of the “Basic Information” screen  where I have been looking for the “About” field in which new users enter their purpose to join PSAP. Jennifer wants me to check that information (and sometimes edit if needed.) Is this where I can find that information?
[cid:image003.jpg@01D152C0.BAD69AC0]

Thanks,
Miriam

**Comment by adolski** [comment]
@miriamcenteno Sorry, this hasn't been deployed yet -- I'm going to bundle this latest batch of work together (everything in the "1.0.2" milestone) and deploy it all at once when it's complete. I hope to have that done this week.
