### ISSUE TITLE
Revert delete action on PSAP?

### ISSUE THREAD

**Issue by miriamcenteno** [PresConsUIUC/PSAP#340]
PSAP user deleted repository by mistake. Can it be restored? See below:

From: 
Sent: Wednesday, March 9, 2016 12:10 PM
To: UI-LIB-PSAP
Subject: revert delete action on PSAP?

Hello:

I just accidentally deleted the repository location I had all of my resources in… is there any way we can revert this mistake?? Please help!

Sincerely,

**Comment by adolski** [comment]
(Response via email)

**Comment by miriamcenteno** [comment]
Can these three things be done?
1. Obtain a dump of the file from last night’s back up- Jennifer is willing to try to ID the records for her institution
2. Get the records back into the system- we are not sure how we could do it
3. Add an “are you SURE you want to delete this [location, record, institution]” pop up to all delete buttons

**Comment by adolski** [comment]
Re: 1 and 2: The backups are SQL files containing all of the commands to load all of the data into an empty database. They are not in "human" format. Without getting into all of the details, it would be a horrendous job.

Re: 3: I do sympathize with the user here, and I am open to ideas on making the delete process safer, but no matter what we do, we should expect that mistaken deletes are going to happen from time to time. All delete buttons already have confirmation popups, and these can protect against accidental clicks, but it's not really possible to ward off intentional clicks that the user finds to be mistaken after the fact. (Which is why Windows has a "Recycle Bin," for example.)

**Comment by jhain** [comment]
Thanks, Alex.  OK, so the user in question actually clicked “delete location” and then confirmed the delete?  (she asked for such a function to be added, which made me think that she did not confirm the delete). I agree that if this is already in place, we don’t need three levels of delete confirmation.  How had would it be, though, to throw in something like this in the confirmation/warning popup?

“are you SURE you want to delete this location? Doing so will delete XX items”

**Comment by jhain** [comment]
Sure, let’s scare the wits out of them.  In the meantime, Miriam, do you want to write to the user and say that to the best of our knowledge she DID click on the “are you sure” message to confirm the delete? Or do you want me to have the pleasure ☺

J

**Comment by miriamcenteno** [comment]
Jennifer,

I think that it might come better from you. I also think that we may have to explain to people that recovering their data is not possible so that they are not expecting it’s restoration. Perhaps we should encourage them to generate/ download frequent reports. I am not familiar enough with PSAP enough to know if people can back up their own data.

Miriam

**Comment by jhain** [comment]
They can do data dumps, but it wouldn’t be easy to get it back into the PSAP. more feasible it sounds like than from the SQL back up, but still a royal pain in the bottom from the resultant CSV.

But yes, I will add this to the online documentation so that it’s up there. And I will write back to the user.

Jennifer

**Comment by adolski** [comment]
Open for feedback:

## Delete institution (admins only)

#### Current

Deleting this institution will delete ALL of its repositories, locations, and resources along with it. Are you sure you want to do this?

#### New

Same

## Delete repository

#### Current

Deleting this repository will delete all locations and resources it contains. Are you sure you want to delete this repository?'

#### New

Deleting this repository will delete all locations and resources it contains. Are you sure you want to delete this repository?'

☠️ WARNING: THIS CANNOT BE UNDONE! ☠️

## Delete location

#### Curren

Deleting this location will also delete all resources it contains. Are you sure you want to delete this location?

#### New

Deleting this location will also delete all resources it contains. Are you sure you want to delete this location?

☠️ WARNING: THIS CANNOT BE UNDONE! ☠️

## Delete resource

#### Current

Are you sure you want to delete this resource?

#### New

Are you sure you want to delete this resource? Any child resources will also be deleted.

☠️ WARNING: THIS CANNOT BE UNDONE! ☠️

**Comment by miriamcenteno** [comment]
I especially like the skull & bones in the extra warning. Should give them pause!

**Comment by jhain** [comment]
Agreed.

**Comment by elviaa** [comment]
Hello, I am the PSAP user that experienced this -- 


I just retraced my steps by creating a dummy location and sub-resource within this dummy location. I originally wanted to delete a dummy sub-resource I was playing with within the location I deleted. My mistake was that I attempted to delete this record in this view (see below). 
![deletepopup](https://cloud.githubusercontent.com/assets/13053146/13755992/2ca534ac-e9f4-11e5-85f7-adaad1a50cfb.jpg)

There is no delete button to delete a single sub-resource in this view. There is the option to check individual sub-resources, but only to move them. One would have to first click on the sub-resource and then hit delete in this view. As you can see, this is an understandable action a user would attempt to do from this view. Also, the pop-up window looks so commonplace that I automatically confirmed the action without reading what the action will do.

Skulls and all caps for this pop-up will definitely help next time ;) Also, if possible, an Undo button?

Best,
Elvia Arroyo-Ramirez

**Comment by adolski** [comment]
Thanks for illustrating this, @elviaa. I agree that the use case here is confusing. I will look into adding a "Delete Checked" button next to "Move Checked."

(An undo button is unfortunately difficult to achieve.)

**Comment by adolski** [comment]
Confirmation pop-up enhancements deployed; ended up using ⚠️ rather than ☠️ as it is a little more noticeable/clearer. Moved "Delete Checked" button to #341.
