### ISSUE TITLE
Reset password for enabled user

### ISSUE THREAD

**Issue by miriamcenteno** [PresConsUIUC/PSAP#342]
[REDACTED] is having problems accessing her account with this email, the system is telling her that the email is not registered. I checked her status and she is an enabled user. How can her access be restored?

**Comment by adolski** [comment]
It's registered -- please just direct her to the forgot-password page (click the "Forgot?" link next to the password field on the main page).

**Comment by miriamcenteno** [comment]
Hi Alex,

Thank you, I think she is all set up now.

Miriam
