### ISSUE TITLE
Assessment Type (?) icon error

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#344]
When starting a new assessment, in assessment box, click on "Assessment Type" (?) icon, box opens up with blue "More Information". When click on "more information" - get page with error message: 
"Not Found
The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved."

pic:
![assessment type error](https://cloud.githubusercontent.com/assets/19311155/19039955/8ddb303a-8947-11e6-830c-cf90d65e987c.JPG)

**Comment by adolski** [comment]
The "more information" link points to /format-id-guide/assessmentssurveys, which came from assessmentssurveys.html in the bundle, but it looks like that file does not exist. Weird that no one else ever caught this. But, just let me know where the link should point to, and I will fix it.

**Comment by suhailsheth** [comment]
Hi Alex,
The link should point to /manual#assessments.
