### ISSUE TITLE
Change from FIDG to CIDG (permanent redirect)

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#345]
Creating this issue per Alex's request.
THIS issue is regarding Alex's changes. He says: "There are some other links into the FIDG from elsewhere in the application that I will change myself. I will also install a permanent redirect from /format-id-guide/whatever to /collections-id-guide/whatever"

Regarding the changes from FIDG to CIDG in HTML: Suhail is making changes from "format" to "Collections" in the HTML and the links in the HTML as per Alex's request ("for all of the links that contain "/format-id-guide" that you are able to change, please change them to include "/collections-id-guide" instead.")

**Comment by adolski** [comment]
This is now done and available for testing (with updated content from the G: drive) on psap-stage.library.illinois.edu.
