### ISSUE TITLE
Building OBJECTS into FIDG/CIDG TOC

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#346]
Comparing to the current FIDG, "Objects" will be on the same "level" as AV, Paper & Book, Photo & Image material, and Supplementary. 

Under Objects, in the grey bar at the top of the box: [square image] Objects (the [square image] can be any of the ones in the images folder in the objects file of the HTML on the Gdrive. Maybe teracottabowl.jpg, stonewaresugarbowl.jpg, or silverbow.jpgl). 

Then IN the "Objects" box, "Objects in General" and "Object Materials"  (on par with "Paper" and "Ink & Other Media" under Unbound Paper in current FIDG.

Objects in General needs to be hyperlinked/connected to the museumobjects html file. Beneath Objects in General, we can list the sections of that doc, hyperlinked so that clicking on them will take users directly to that part of the file. Here's the list (but they don't need to be underlined, that's just how they copied over when I cut and paste):
Is it glass, stone, or ceramic?
Object Surfaces
Previous Residue
Previous Repairs
Storage of Objects
Handling Objects
Labelling Objects
Display Objects
Archaeological Objects

Object Materials should be hyperlinked/connected to the objectmaterials html file, BUT it can also have breakdowns by object material type (**Ceramic, Glass, Stone, Metal**) that will go to those specific parts of the html file (similar to how ball-point pen, carbon black ink, etc. are broken down under "Ink & Other Media" now. 

Thanks.

**Comment by adolski** [comment]
Objects section now available on psap-stage. Feel free to reopen if any changes are required.

**Comment by spelczar** [comment]
thanks.

Somer Pelczar
Visiting IMLS Project Manager
Preservation Self-Assessment Program
University of Illinois Library, Preservation Services
https://psap.library.illinois.edu/
________________________________

**Comment by spelczar** [comment]
Alex, can we also add "Objects" to the Collection ID Guide pull-down at the top left of the screen?

**Comment by adolski** [comment]
Done.
