### ISSUE TITLE
PSAP Extension: Question Dependencies spreadsheet ready

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#348]
The updated Question Dependencies excel document is ready -- on the G drive in AcqCatPres > PSAP > Scores folder.

**Comment by adolski** [comment]
@spelczar Thanks. This is really great work. I've got all of the new spreadsheet content imported on my local machine, and it appears to be working without any hitches, but I want to do some more testing before pushing it out to psap-stage, maybe tomorrow or Thursday -- I'll let you know.

**Comment by adolski** [comment]
@spelczar One other thing I should let you know about is that unlike the HTML, the spreadsheet content can only be loaded once in production. When people begin assessing their materials, associations are created in the database between their resources and the various questions, and reloading the questions would break the associations.

This doesn't apply to psap-stage, though, as that's all test data.

**Comment by spelczar** [comment]
Thanks Alex. Speaking of not messing with assessments that have already been performed: I forgot to mention that we DID also make minor tweaks to the **Institutions** sheet in the spreadsheet. The changes typically were to make the wording more inclusive so those questions could also apply to objects. Fewer than 10 of the institution questions were tweaked, and I think we only had to make 2 changes in the answer options (adding an "NA" and changing an "Unsure" to "Unsure/NA").

**Comment by adolski** [comment]
Do you remember which ones you tweaked? I will have to update them manually. Sorry, I should have let you know earlier.

**Comment by spelczar** [comment]
You did, I just got caught up in the new sheets that I forgot to mention these tweaks. I have a GOOGLE doc spreadsheet that shows the changes clearly (in red) - can you access the doc via this link?
https://docs.google.com/spreadsheets/d/1R-d2aPnEIFucVD4Cjly5KRbDmZnZzPYNyN58qgQUqwc/edit?usp=sharing

let me know if you can't!

**Comment by adolski** [comment]
I created #349 to track the question tweaks.

Also, I have the object data loaded on psap-stage. Everything appears to be working smoothly, but please let me know if you notice any issues.

**Comment by spelczar** [comment]
Thanks Alex.
We should have the HTML for all the Advanced Help pages done by Friday at the latest. Do you think we could do another HTML ingest then? -- that way we can start checking all the help links and anchors in the assessment tool!

**Comment by adolski** [comment]
Of course.

**Comment by spelczar** [comment]
And I SIGN IN to the psap-stage how? (hasn't been an issue thus far because I've only been viewing the CIDG, so no need to sign in). Is there an admin or "staged" username/password I can use?
