### ISSUE TITLE
The second dependent question disappears when selecting an option of the first

### ISSUE THREAD

**Issue by suhailsheth** [PresConsUIUC/PSAP#350]
When an option of the dependent question, for example question (8a) (Objects->Ceramics->Any Type) is selected, the second dependent question (8b) hides itself. This happens only when there are two dependent questions and I have checked this on the psap-staged website. Below is a screenshot showing the questions.

![image](https://cloud.githubusercontent.com/assets/22619180/19912562/415b8c30-a069-11e6-8985-887f6fa090e8.png)

This happens only when there are two dependent questions and I have checked this on the psap-staged website.

**Comment by adolski** [comment]
Thanks for reporting this, @suhailsheth. The fix has been deployed to psap-stage. (I won't push it to production yet because there are no assessment questions there that would be affected by it.)
