### ISSUE TITLE
Links pointing to section/pages in user-manual/adv-help are broken on PSAP-Stage

### ISSUE THREAD

**Issue by suhailsheth** [PresConsUIUC/PSAP#353]
Links which are directed to any section/page of the user-manual or advance-help in the new Collection ID Guide content seems to have a problem. For example, link to "Use and Access" section in the user-manual has to be "**/manual#useaccess**" (this is what is in the HTML page), but on the PSAP-Stage website it seems to be "**/collection-id-guide/manual#useaccess**". So basically,  "**/collection-id-guide**" is somehow being added to the links pointing outside the collection-id-guide.

**Comment by adolski** [comment]
I think this is fixed now, @suhailsheth. Can you test again (on psap-stage) and make sure?

If it's still not working, please post the URL of a page where it is happening, and let me know which link on the page is not working. Otherwise, please close this issue. Thanks.

**Comment by suhailsheth** [comment]
It seems to be fixed for most links, but I found one which still not working. The page is->**https://psap-stage.library.illinois.edu/collection-id-guide/museumobjects** and the link is in the last line of the first para ->**https://psap-stage.library.illinois.edu/objectmaterials**. In the HTML it points to "/collection-id-guide/objectmaterials".

**Comment by adolski** [comment]
That link will need to be changed in the HTML. When linking within a component (like from one CIDG page to another) the link should not include the path. Examples:

* `<a href="page.html#section">link to a section on different page</a>`
* `<a href="#section">link to a section on the same page</a>`

This link is written as `<a href="/collection-id-guide/objectmaterials">`, so it should be changed to `<a href="objectmaterials.html">`. This new link will work within the CIDG folder bundle, and the application will strip off the `.html` automatically.

**Comment by suhailsheth** [comment]
OK, understood. Thanks

**Comment by suhailsheth** [comment]
I have a doubt, @adolski . How to I link from Adv-help page to CIDG page?

**Comment by adolski** [comment]
`<a href="/collection-id-guide/pagename">`

This link won't work in the bundle, but it will work when it gets into the application.

**Comment by suhailsheth** [comment]
@adolski 

The link to the "handling objects" under the training header in the adv-help ceramics page (https://psap-stage.library.illinois.edu/advanced-help/advhelp-ceramics#training) on the PSAP-Stage Site is ` <a href="/museumobjects#handleobjects">`

BUT, in the HTML it is ` <a href ="/collection-id-guide/museumobjects#handleobjects">`. I am not sure where I am going wrong or maybe the application stripping of **"/collection-id-guide/"** in the adv-help page as well? Please let me know. Thanks.

**Comment by adolski** [comment]
This should be fixed now; please reopen if you notice any more problems. We didn't have any cross-component links in the past, so this functionality wasn't tested.

**Comment by suhailsheth** [comment]
@adolski

The cross-links within components of the CIDG are not working now. I had modified the links in the HTML from `<a href="/collection-id-guide/page#section">` to `<a href="page.html#section">`. All such links now point to **https://psap-stage.library.illinois.edu/page.html#section** instead of  **https://psap-stage.library.illinois.edu/collection-id-guide/page.html#section**.

**Comment by adolski** [comment]
Fixed on psap-stage
