### ISSUE TITLE
Add object content to advanced help landing page

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#354]
Advanced Help Landing page needs addition of "Objects" and object types. See the RED text on the last page of "Advanced Help Landing Page Content" WORD doc in PSAP > Design > EXTENSION HTML> AdvHelp Ext folder on the G-drive (and also attached)
[Advanced Help Landing Page Content.docx](https://github.com/PresConsUIUC/PSAP/files/576581/Advanced.Help.Landing.Page.Content.docx)

**Comment by adolski** [comment]
@spelczar Could you create a separate issue for (2)?

**Comment by spelczar** [comment]
Will do.
