### ISSUE TITLE
"More Information" links in Location (and sometimes Institution) help boxes not working

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#357]
On BOTH the staged site and the live PSAP: in the Location assessment box: if click on (?) icon, and then "more information" hyperlink: always goes to "not found page". Not sure where the Location advanced help HTML files are -- they're not with the format-AdvHelp HTML files on the G drive. 

Also note: this is an issue for the "more information" links in the HELP boxes for INSTITUTION questions too, but only on the STAGED site, NOT on the live PSAP.

**Comment by adolski** [comment]
It looks like there used to be files called `location.html` and `institution.html` in the advanced help bundle, but they got deleted, for some reason. I managed to pull the latest versions I have out of git, and place them back in the `AdvHelp Ext` folder for you to do with as you wish. `location.html` is from 4/23/2015 (it had been renamed `supplementary-location.html` if it matters) and `institution.html` is from 5/25/2015.

If you want to keep them, they will get pulled in on the next ingest. Looks like this will fix all of these "more information" links, so I will close this issue.
