### ISSUE TITLE
Refigure grey bar at top of PSAP

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#361]
Alex how difficult would it be to shuffle some things in the anchored grey bar at the top of the screen? I realize that simplicity is key to helping the screen look good on smaller/mobile devices. These changes would hopefully keep that simplicity - just move things around in ways that may be more helpful to the user.

1) Move Glossary and Bibliography, which are currently anchored on the top bar, out of there, and move them into the first "Supplementary" section "Preservation Self-Assessment Program"

2) Then, in order to make the User Manual more visible: move the book icon that is currently on the upper right (next to the ?)  - move it to next to the "Collection ID Guide" pull down on the upper left side of the bar, and add "USER GUIDE", and make it a pull-down.

3) Then list everything that is listed in the  "Preservation Self-Assessment Program" box in the Supplementary materials section, in the drop-down that comes from the new "User Guide" "button" on the top bar. 

I hope these images help illustrate. 
![topbaredits](https://cloud.githubusercontent.com/assets/19311155/20197515/98f1ab5c-a765-11e6-8a0d-b08be4cbefbd.JPG)
![new bar psap ext](https://cloud.githubusercontent.com/assets/19311155/20197516/9ada0c02-a765-11e6-8b24-e7d4320a7bbc.JPG)

We can leave it so that the "Supplementary" section is still accessible as the last thing on the "Collection ID Guide" pull down and menu - in this case I think redundancy is OK, if it helps people find what they need to navigate the PSAP. 
Same with the  Help (?) icon in the upper right. . . I'd leave it there.  (or even move it so that it is next to "Collection ID Guide" and "User Guide" near the left side of the bar, instead of the right. 

Let me know if we can make this happen, or if it's just too complicated at this point (and should be held for the next grant iteration).
Thanks.

**Comment by adolski** [comment]
I think it would be an improvement, and it would be easy to do.

**Comment by adolski** [comment]
This has been deployed to psap-stage. I left the help icon in the top right (I think that's a usability principle, although I can't justify it off the top of my head) and removed the book icon from the user guide item to be consistent with the CIDG item. All of the icons are from http://fontawesome.io/icons/, if you want these to be re-iconified.
