### ISSUE TITLE
Second question adv-help link in Location Assessment is broken

### ISSUE THREAD

**Issue by suhailsheth** [PresConsUIUC/PSAP#367]
@adolski 

Hi,

The second question, which is "What is the annual average temperature for this location?", advanced help link from the help pop-up in the location assessment questions is broken.

The links currently leads to `/advanced-help/location#location-q1b` instead of `/advanced-help/location#location-q2-3`. This issue was fixed in the "Question Dependencies" excel sheet but for some reason has not showed up on the PSAP-Stage website.

Thanks,
Suhail

**Comment by adolski** [comment]
Thanks for reporting this -- it is now fixed on psap-stage. Changes to non-object questions in the spreadsheet (like this) aren't going to make it in automatically -- I will have to do them manually.

**Comment by suhailsheth** [comment]
You're Welcome!
