### ISSUE TITLE
Extension beta testing - alert on main page

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#368]
@jhain @adolski 
How's this for the announcement of the beta version on the main page, to go with the launch?
(a little more wordy than the last announcement, since this launch is just a portion of the larger PSAP)

"The PSAP has been updated to include inorganic museum objects! In addition to some small functional changes to the site, the PSAP resources and assessment tool now cover ceramic, glass, stone, and metal object materials. This **beta version** of the objects portion of the application is functional, but some things may change. Feedback on these additions and changes are welcome and can be sent to  psap@library.illinois.edu."

**Comment by jhain** [comment]
works for me!

**Comment by adolski** [comment]
Can I prepend "November 21, 2016:" to that?

**Comment by spelczar** [comment]
Yep!

**Comment by jhain** [comment]
yes, makes sense
