### ISSUE TITLE
Ready for launch, except two images

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#369]
@adolski @suhailsheth

Alex, everything looks good and we're ready for launch, except there are two images that are continuing to cause problems: roachleavings and moldyrecordingcontainer images - both in the Pest/Mold section of AdvHelp for ceramics, glass, metal, and stone- aren't showing up. These were among the images that weren't showing up a few HTML ingests ago -- changing the capitalization in the image names seemed to solve the problem for all **but** these two images.

Thing is: both these images exist elsewhere in the PSAP - in old advanced help pages. And they show up fine in all the old advanced help pages AND when viewing the HTML. It's just on the staged site for those 4 AdvHelp pages that they won't show up. So today I adjusted the html one more time, and changed the names of those two images in the 4 object advanced help files to exactly match the names of the images in all the other advanced help pages.

Not sure how difficult it is to fix something like a missing image AFTER the launch - so I'll leave it up to you to see if you want to do another html ingest for PSAP STAGED first, just to see if these two images work, before doing the launch, OR if you want to just go ahead and launch. 

Aside from those two images (and the dependent questions fix that is coming later), we're all set for launch.

Thanks

**Comment by adolski** [comment]
Image problem was a remnant of #356, now fixed on psap-stage.

**Comment by spelczar** [comment]
NOW the two images that weren't showing up properly in the 4 Object AdvHelp pages - work fine in Objects, but NOT all the other AdvHelp pages.  ?

**Comment by adolski** [comment]
This is fixed on psap-stage; will be fixed in production this afternoon. I will close it then.
