### ISSUE TITLE
typo fixes on CIDG landing page

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#371]
@adolski  can you make TWO small fixes to CIDG landing page? ..under Objects > Objects in General: 
1. Labelling should only have one "l" in the word (not counting the L it starts with).. should be **Labeling**
2. Change "Display Objects" to "Displaying Objects"
![cidglandingtypos](https://cloud.githubusercontent.com/assets/19311155/20679527/ea4b310e-b560-11e6-8178-484468e143ad.JPG)

thanks

**Comment by adolski** [comment]
On psap-stage now; will deploy when #351 is confirmed resolved.
